### ISSUE TITLE
Support for query_string filtering?

### ISSUE THREAD

**Issue by anryangelov** [barseghyanartur/django-elasticsearch-dsl-drf#169] opened 2019-12-02 16:51 UTC
Is there any plans for implementing query_string (lucene_search) backend filtering?

**Comment by barseghyanartur** [comment] 2019-12-02 17:55
Duplicate of https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/issues/65

**Closed by barseghyanartur** 2019-12-02 17:55 UTC

**Comment by barseghyanartur** [comment] 2019-12-02 18:00
There are plans, yes, however, I'm not sure when will I have time for it. You could, however, speed up the development by sponsoring this feature. Contact me for the details, if you wish.
