### ISSUE TITLE
Is there a way to show filter options in the DRF Browsable API UI?

### ISSUE THREAD

**Issue by metalshanked** [barseghyanartur/django-elasticsearch-dsl-drf#286] opened 2022-03-02 19:38 UTC
I am currently planning to switch from a PG backend to Elastic.
One of the features with using PG was that it showed field filters created by `django-filters` in the built in DRF Browsable API UI

These don't show up in the UI when using the `django-elasticsearch-dsl-drf` built in Lookup filters.
Any way this can be made to show up in the UI?

<img width="612" alt="2022-03-02_12-36-28" src="https://user-images.githubusercontent.com/57646596/156436389-551545f2-bf40-4b94-9284-c349db022a62.png">

Thanks in advance!

**Comment by barseghyanartur** [comment] 2022-07-02 21:33
ATM - not. This issue will be likely picked as a priority in the future.

**Comment by barseghyanartur** [comment] 2022-07-02 21:34
Actually, duplicate of https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/issues/283

**Closed by barseghyanartur** 2022-07-02 21:34 UTC
Labels: enhancement, question
