### ISSUE TITLE
Extra query when getting a single object

### ISSUE THREAD

**Issue by Alexgmin** [barseghyanartur/django-elasticsearch-dsl-drf#16] opened 2017-11-09 17:47 UTC
https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/blob/2bfec6e43dfedcb72d4d709cb5267e454d1c5e06/src/django_elasticsearch_dsl_drf/viewsets.py#L72

The queryset.count() should be done after executing the query.

Since what's going to happen most of the time it's that you get a single result, I don't see why it's necesary to avoid doing the query when you're going to get more than one result, when you can check this later and avoid doing the count query.

Great job on this package, btw.

**Comment by barseghyanartur** [comment] 2017-11-09 20:44
@Alexgmin:

I need to investigate this.

**Comment by barseghyanartur** [comment] 2018-06-27 20:16
@Alexgmin:

This issue is apparently solved, as I can't reproduce it anymore. Closing.

**Closed by barseghyanartur** 2018-06-27 20:16 UTC
Labels: investigate, work in progress

**Comment by Alexgmin** [comment] 2019-07-08 14:54
As far as I can see, this still happens, and the code causing this has not changed:
https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/blob/c690224f3abbf3209429e20739270592483dee5f/src/django_elasticsearch_dsl_drf/viewsets.py#L226-L228

Changing it to this seems to fix it without any other problems other than the one specified earlier. 
```python
            obj = queryset.execute().hits.hits[0]['_source']
            count = queryset.count()
            
            if count == 1:
```

This is because the count method checks if it already has the results before doing a new query.
https://github.com/elastic/elasticsearch-dsl-py/blob/85dafe6a3d4937b1db45204dc618ab02f57c968b/elasticsearch_dsl/search.py#L664-L680

**Comment by barseghyanartur** [comment] 2019-07-10 08:39
@Alexgmin:

Thanks. I'll check it as soon as possible. You could also come up with a pull request. Travis is up-and-running, thus, it will be easy to see if all goes well.
