### ISSUE TITLE
ConnectionTimeout and ConnectionError when updating search index

### ISSUE THREAD

**Issue by turukawa** [barseghyanartur/django-elasticsearch-dsl-drf#123] opened 2019-04-02 08:27 UTC
Hi,

I am running Django 2.1 plus DRF on Ubuntu 18.04 and Elasticsearch 6.5. I have a search index of about 1.8 million records which is updated once a quarter and needs to be reindexed.

I have a Celery task which runs an automated process to perform this immediately after the data and record update:

`management.call_command("search_index", "--populate", "-f", verbosity=0)`

Which is equivalent to the command-line code:

`python manage.py search_index --populate -f`

This worked until recently when the index went from about 1.4 million records to 1.8 million. When run, after about three hours, I get one of the following two error messages:

`{"exc_type": "ConnectionTimeout", "exc_message": ["TIMEOUT", "HTTPConnectionPool(host='localhost', port=9200): Read timed out. (read timeout=10)", "ReadTimeoutError(\"HTTPConnectionPool(host='localhost', port=9200): Read timed out. (read timeout=10)\",)"], "exc_module": "elasticsearch.exceptions"}`

or 

`{"exc_type": "ConnectionError", "exc_message": ["N/A", "<urllib3.connection.HTTPConnection object at 0x7f4d40ff3ef0>: Failed to establish a new connection: [Errno 111] Connection refused", "NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4d40ff3ef0>: Failed to establish a new connection: [Errno 111] Connection refused',)"], "exc_module": "elasticsearch.exceptions"}`

I've no idea what to do. Searching results in issues related to `timeout` or `chunk_size` (e.g. [via StackOverflow](https://stackoverflow.com/questions/31576270/elasticsearch-python-client-reindex-timedout)).

I'm not sure how to set either of these settings. This doesn't work:

`python manage.py search_index --populate -f --timeout=14400 --chunk_size=50`

There is a `settings` flag, but I'm not sure what the syntax for using it should be, or even whether this is correct.

Help much appreciated...

**Comment by barseghyanartur** [comment] 2019-04-02 09:45
@turukawa:

There's an issue open (for some time already) at [django-elasticsearch-dsl](https://github.com/sabricot/django-elasticsearch-dsl/issues/137) addressing the problem.

It's not directly related to this library, but I could spend some time on it (to test and try to speed up the development). Contact me for the details.

**Comment by barseghyanartur** [comment] 2019-04-08 14:51
The issue is documented [here](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/blob/master/docs_src/indexing_troubleshooting.rst) and will be included in the official docs.

**Closed by barseghyanartur** 2019-04-08 14:51 UTC

**Comment by ivoytov** [comment] 2020-12-23 19:10
The above link is dead and I'm having the same issue

> The issue is documented [here](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/blob/master/docs_src/indexing_troubleshooting.rst) and will be included in the official docs.

**Comment by barseghyanartur** [comment] 2020-12-23 22:20
@ivoytov:

Searching in the [documentation](https://django-elasticsearch-dsl-drf.readthedocs.io/en/latest/indexing_troubleshooting.html) might be a good first tip for the next time.

**Comment by barseghyanartur** [comment] 2020-12-23 22:22
As of the issue, I think at the moment, standard `django-elasticsearch-dsl` does support parallel indexing. No need to install it from fork.

**Comment by ivoytov** [comment] 2020-12-24 16:39
Thanks for the pointer, this resolved my issue.
